---
title: "Introduction to Data in R"
output: html_document
---

#Chapter 3 Sampling strategies and experimental design 


```{r}
# Simple random sample: states_srs
states_srs <- us_regions %>%
  sample_n(size= 8)

# Count states by region
states_srs %>%
  count(region)
```


```{r}
# Stratified sample
states_str <- us_regions %>%
  group_by(region) %>%
  sample_n(size=2)

# Count states by region
states_str %>%
  count(region)
```


#Chapter 4 Case study

```{r}
# Inspect variable types
str(evals)

# Remove non-factor variables from the vector below
cat_vars <- c( "rank", "ethnicity", "gender", "language",
               "cls_level", "cls_profs", "cls_credits", "pic_outfit", "pic_color")
```


```{r}
# Recode cls_students as cls_type
evals_fortified <- evals %>%
  mutate(
    cls_type = case_when(
      cls_students <= 18                      ~ "small",
      cls_students >= 19 & cls_students <= 59 ~ "midsize",
      cls_students >= 60                      ~ "large"
    )
  )
```

```{r}
# Scatterplot of score vs. bty_avg
ggplot(evals, aes(x=bty_avg, y= score)) +
  geom_point()
```

```{r}
# Scatterplot of score vs. bty_avg colored by cls_type
ggplot(evals, aes(x= bty_avg, y= score, color= cls_type)) +
  geom_point()
```

